// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfANSkIQGPD7A8meCIjFboUmih0kL58uI',
    appId: '1:287326020953:web:5588ac24b3e471e78d5848',
    messagingSenderId: '287326020953',
    projectId: 'signin-example-5e558',
    authDomain: 'signin-example-5e558.firebaseapp.com',
    storageBucket: 'signin-example-5e558.appspot.com',
    measurementId: 'G-9949RV40LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHRUfbbOOU_-1Xy8H4W-_FN6lAC2FGw0',
    appId: '1:287326020953:android:d8a939b09e6b27b38d5848',
    messagingSenderId: '287326020953',
    projectId: 'signin-example-5e558',
    storageBucket: 'signin-example-5e558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdeeEqh-60MP-iCFNnOgzQp8kKXGO9-sk',
    appId: '1:287326020953:ios:56ac4ff74e1c87308d5848',
    messagingSenderId: '287326020953',
    projectId: 'signin-example-5e558',
    storageBucket: 'signin-example-5e558.appspot.com',
    iosBundleId: 'com.example.lostnfoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdeeEqh-60MP-iCFNnOgzQp8kKXGO9-sk',
    appId: '1:287326020953:ios:56ac4ff74e1c87308d5848',
    messagingSenderId: '287326020953',
    projectId: 'signin-example-5e558',
    storageBucket: 'signin-example-5e558.appspot.com',
    iosBundleId: 'com.example.lostnfoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfANSkIQGPD7A8meCIjFboUmih0kL58uI',
    appId: '1:287326020953:web:ea96dc44b0f149d18d5848',
    messagingSenderId: '287326020953',
    projectId: 'signin-example-5e558',
    authDomain: 'signin-example-5e558.firebaseapp.com',
    storageBucket: 'signin-example-5e558.appspot.com',
    measurementId: 'G-3DLP4FFPMS',
  );
}
